using DevExpress.XtraCharts;
using DevExpress.XtraGrid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace is_takip_proje.Formlar
{
    public partial class FrmDepartmanİstatistikleri : Form
    {
        public FrmDepartmanİstatistikleri()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // ChartControl'e bir seri ekleme
            Series series = new Series("Satışlar", ViewType.Bar);

            // Seri verilerini ekleme
            series.Points.Add(new SeriesPoint("Ocak", 100));
            series.Points.Add(new SeriesPoint("Şubat", 120));
            series.Points.Add(new SeriesPoint("Mart", 140));
            series.Points.Add(new SeriesPoint("Nisan", 130));
            series.Points.Add(new SeriesPoint("Mayıs", 150));

            // Seriyi ChartControl'e ekleme
            chartControl1.Series.Add(series);

            // Grafik başlığı ekleme
            ChartTitle chartTitle = new ChartTitle();
            chartTitle.Text = "Aylık Satışlar";
            chartControl1.Titles.Add(chartTitle);
        }
    }
}


